#!/bin/bash
################################################################################
# rhiginとコンポーネントに関係するプロジェクトの全コンパイル.
################################################################################

# 現在のパスを保持.
NOW_PATH=` pwd`

# projectパス.
PROJECT_PATH="${RHIGIN_HOME}/../.."

################################################
# objectpackプロジェクト を cloneしてコンパイル.
################################################

# objectpackプロジェクトパス.
OBJECT_PACK_PATH="${PROJECT_PATH}/objectpack"

# objectpackのプロジェクトフォルダが存在するかチェック.
if [ -f ${OBJECT_PACK_PATH}/build.xml ]; then
    # 更新チェック.
    cd ${OBJECT_PACK_PATH}
    git pull origin master;
else
    # 存在しない場合は、gitからclone.
    cd ${PROJECT_PATH}
    git clone https://github.com/maachang/objectpack.git
    if [ $? != 0 ]; then
        cd ${NOW_PATH}
        exit 1
    fi
fi

# objectpackパスに移動.
cd ${OBJECT_PACK_PATH}
if [ $? != 0 ]; then
    cd ${NOW_PATH}
    echo "The specified leveldb path does not exist: ${OBJECT_PACK_PATH}"
    exit 1
fi

# objectpackをコンパイル.
ant clean
ant
if [ $? != 0 ]; then
    cd ${NOW_PATH}
    exit 1
fi

# コンパイル結果の jar ファイルを rhigin のプロジェクトライブラリ or rhiginHomeのライブラリ に 削除 or コピー.
mkdir -p ${PROJECT_PATH}/rhigin/project/lib/
mkdir -p ${RHIGIN_HOME}/lib/
rm -Rf ${PROJECT_PATH}/rhigin/project/lib/objectpack-*.jar
rm -Rf ${RHIGIN_HOME}/lib/objectpack-*.jar
cp objectpack-*.jar ${PROJECT_PATH}/rhigin/project/lib/
cp objectpack-*.jar ${RHIGIN_HOME}/lib/

######################
# rhiginのコンパイル.
######################
cd ${NOW_PATH}
ant clean
ant

##################################################
# leveljs に対するleveldbプロジェクトのコンパイル.
##################################################
sh components/leveljs/libjar
if [ $? != 0 ]; then
    cd ${NOW_PATH}
    exit 1
fi

cd ${NOW_PATH}
exit 0