#!/bin/bash
################################################################################
# leveldb のライブラリをコンパイルして jar をproject/lib 配下にセットする.
################################################################################
COMPONENT_NAME=leveljs

# プロジェクトパス.
PROJECT_PATH="${RHIGIN_HOME}/../../"

# 現在のパスを保持.
NOW_PATH=` pwd`

# コンポーネントパスをセット.
COMPONENT_PATH="${RHIGIN_HOME}/../components/${COMPONENT_NAME}"

# leveldbのパスを取得.
LEVELDB_PATH="${PROJECT_PATH}/leveldb"

# leveldbのプロジェクトフォルダが存在するかチェック.
if [ -f ${LEVELDB_PATH}/build.xml ]; then
    # 存在する場合は何もしない.
    echo ""
else
    # 存在しない場合は、gitからclone.
    cd ${PROJECT_PATH}
    git clone https://github.com/maachang/leveldb.git
    if [ $? != 0 ]; then
        cd ${NOW_PATH}
        exit 1
    fi
fi

# leveldbパスに移動.
cd ${LEVELDB_PATH}
if [ $? != 0 ]; then
    cd ${NOW_PATH}
    echo "The specified leveldb path does not exist: ${LEVELDB_PATH}"
    exit 1
fi

# antコンパイル.
ant clean
ant
if [ $? != 0 ]; then
    cd ${NOW_PATH}
    exit 1
fi

# 削除 or コピー.
rm -Rf ${COMPONENT_PATH}/project/lib/leveldb-*.jar
cp leveldb-*.jar ${COMPONENT_PATH}/project/lib/

cd ${NOW_PATH}
exit 0